import { Home, Settings, Users, Server } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { BroCardModel, NavItem } from "./types";

export const navItems: Array<NavItem & { icon: LucideIcon }> = [
  { label: "Home", icon: Home, active: false },
  { label: "Bros", icon: Users, active: false },
  { label: "Nodes", icon: Server, active: false },
  { label: "Settings", icon: Settings, active: false },
];

export const sampleBros: BroCardModel[] = [
  {
    id: "atlas",
    name: "Atlas",
    role: "Travel researcher",
    status: "busy",
    liveState: "live",
    executorNodeId: "node-atlas",
    nodeName: "Studio Mac",
    avatarType: "fox",
    taskTitle: "Compare routes and fares",
    progress: 72,
    progressLabel: "72% synced",
    progressDetails: [
      "Checked 12 route combinations across air and rail.",
      "Shortlisted 3 lower-fare options for review.",
      "Verifying refund rules and transfer risk.",
      "Bound to Studio Mac and ready for local execution.",
    ],
    idleNote: "Currently searching across airline and rail websites with Studio Mac online.",
    source: "sample",
  },
  {
    id: "scout",
    name: "Scout",
    role: "Availability checker",
    status: "idle",
    liveState: "offline",
    executorNodeId: "node-scout",
    nodeName: "Travel Laptop",
    avatarType: "cat",
    taskTitle: "Waiting for assignment",
    progress: 0,
    progressLabel: "Idle",
    progressDetails: [
      "Ready to verify schedules and remaining inventory.",
      "Can jump in when a route is selected.",
      "Bound node is offline and needs to reconnect.",
    ],
    idleNote: "Can verify timing once Travel Laptop reconnects.",
    source: "sample",
  },
  {
    id: "muse",
    name: "Muse",
    role: "Planner",
    status: "idle",
    liveState: "unbound",
    executorNodeId: null,
    nodeName: null,
    avatarType: "bunny",
    taskTitle: "Waiting for assignment",
    progress: 0,
    progressLabel: "Idle",
    progressDetails: [
      "Ready to synthesize options into a final recommendation.",
      "Can structure tradeoffs and next steps clearly.",
      "Needs an executor node binding before becoming live.",
    ],
    idleNote: "Can synthesize options after being bound to a node.",
    source: "sample",
  },
  {
    id: "forge",
    name: "Forge",
    role: "Operator",
    status: "busy",
    liveState: "live",
    executorNodeId: "node-forge",
    nodeName: "Workshop Mini",
    avatarType: "bro",
    taskTitle: "Prepare execution steps",
    progress: 43,
    progressLabel: "43% prepared",
    progressDetails: [
      "Drafted booking sequence for the top 2 options.",
      "Checking hold windows and payment ordering.",
      "Preparing fallback flow if preferred option fails.",
      "Workshop Mini is connected and ready to execute.",
    ],
    idleNote: "Can turn decisions into concrete actions with Workshop Mini online.",
    source: "sample",
  },
];
